# Generated by Django 3.1.7 on 2021-03-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210318_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
